FROM node:18

WORKDIR /app

RUN apt-get update && apt-get install -y libssl-dev default-mysql-client

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# ✅ เพิ่มสิทธิ์รัน entrypoint
RUN chmod +x entrypoint.dev.sh

# ✅ เปิดพอร์ต dev
EXPOSE 3000

# ✅ รัน dev ผ่าน script
CMD ["./entrypoint.dev.sh"]
