FROM node:18

WORKDIR /app

RUN apt-get update && apt-get install -y libssl-dev default-mysql-client

COPY package.json package-lock.json ./
RUN npm install --production

COPY . .
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
