services:
  frontend:
    build:
      context: ./frontend
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
    # restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    # restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-service
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    # restart: always

volumes:
  db-data: